from __future__ import annotations

import json

import httpx
import pytest

from backend.app.agents.asklepios_backend import AsklepiosHttpBackend, AsklepiosServiceError
from backend.app.agents.health_navigator import HealthNavigator
from backend.app.agents.contracts import SpecialistName


@pytest.mark.asyncio
async def test_asklepios_adapter_sends_only_narrow_health_contract():
    captured = {}

    async def handler(request: httpx.Request) -> httpx.Response:
        captured["path"] = request.url.path
        captured["body"] = json.loads(request.content.decode("utf-8"))
        captured["authorization"] = request.headers.get("Authorization")
        return httpx.Response(
            200,
            json={
                "reply": "Please seek clinical assessment.",
                "clinical_service_key": "ct_scan",
                "urgency": "urgent",
            },
        )

    client = httpx.AsyncClient(transport=httpx.MockTransport(handler), base_url="https://asklepios.test")
    backend = AsklepiosHttpBackend(
        base_url="https://asklepios.test",
        token="secret",
        client=client,
    )
    try:
        result = await backend.handle(
            case_id=None,
            message="I have severe stomach pain",
            context={
                "language": "en",
                "health_history": [{"role": "user", "content": "pain"}],
                "premium": 1234,
                "policy_wording": "must never cross into Asklepios",
            },
        )
    finally:
        await client.aclose()

    assert captured["path"] == "/v1/navigate"
    assert captured["authorization"] == "Bearer secret"
    assert set(captured["body"]) == {"case_id", "message", "language", "history"}
    assert "premium" not in captured["body"]
    assert "policy_wording" not in captured["body"]
    assert result["benefit_key"] == "ct_scan"


@pytest.mark.asyncio
async def test_health_navigator_never_falls_back_to_hal_on_asklepios_failure():
    async def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(503, json={"detail": "down"})

    client = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    backend = AsklepiosHttpBackend(base_url="https://asklepios.test", client=client)
    navigator = HealthNavigator(backend=backend)
    try:
        result = await navigator.handle(case_id=None, message="severe pain", context={})
    finally:
        await client.aclose()

    assert result.specialist == SpecialistName.HEALTH_NAVIGATOR
    assert result.status == "unavailable"
    assert "No health answer was generated by HAL" in (result.reply or "")


def test_asklepios_adapter_is_disabled_without_service_url(monkeypatch):
    monkeypatch.delenv("ASKLEPIOS_API_URL", raising=False)
    assert AsklepiosHttpBackend.from_environment() is None


def test_asklepios_adapter_rejects_non_http_endpoint():
    with pytest.raises(ValueError):
        AsklepiosHttpBackend(base_url="javascript:alert(1)")
