from __future__ import annotations

from typing import Any, Protocol
import os
from uuid import UUID

from .asklepios_backend import AsklepiosHttpBackend, AsklepiosServiceError
from .contracts import SpecialistName, SpecialistResponse


class HealthNavigatorBackend(Protocol):
    async def handle(
        self,
        *,
        case_id: UUID | None,
        message: str,
        context: dict[str, Any],
    ) -> dict[str, Any]: ...


class HealthNavigator:
    """Asklepios adapter boundary.

    Asklepios/Kira remains a separate health specialist service. HAL never
    imports Kira's implementation code directly. Health model calls stay inside
    the health service, while health-to-insurance transfer remains consent-gated.
    """

    name = SpecialistName.HEALTH_NAVIGATOR

    def __init__(self, backend: HealthNavigatorBackend | None = None):
        self.backend = backend

    async def handle(
        self,
        *,
        case_id: UUID | None,
        message: str,
        context: dict[str, Any] | None = None,
    ) -> SpecialistResponse:
        ctx = dict(context or {})
        if self.backend is None:
            return SpecialistResponse(
                specialist=self.name,
                status="handoff",
                reply="Continue health navigation in Asklepios using the workspace link. No clinical information is transferred automatically." if os.getenv("ASKLEPIOS_WEB_URL") else "This request belongs to Asklepios. The health-service endpoint is not configured in Adviser OS yet.",
                payload={
                    "target": "asklepios",
                    "handoff_url": os.getenv("ASKLEPIOS_WEB_URL"),
                    "case_id": str(case_id) if case_id else None,
                    "consent_required_for_insurance_transfer": True,
                },
            )

        try:
            result = await self.backend.handle(case_id=case_id, message=message, context=ctx)
        except AsklepiosServiceError as exc:
            return SpecialistResponse(
                specialist=self.name,
                status="unavailable",
                reply="Asklepios is temporarily unavailable. No health answer was generated by HAL as a fallback.",
                payload={
                    "target": "asklepios",
                    "error": str(exc)[:240],
                    "consent_required_for_insurance_transfer": True,
                },
            )

        reply = str(result.get("reply") or "")
        payload = dict(result)
        payload["consent_required_for_insurance_transfer"] = True
        return SpecialistResponse(
            specialist=self.name,
            status="completed",
            reply=reply,
            payload=payload,
        )


def get_health_navigator() -> HealthNavigator:
    """Build the navigator from deployment configuration.

    With no ASKLPIOS/ASKLEPIOS service URL configured, HAL fails safely into a
    handoff instead of attempting its own medical model call.
    """
    backend = AsklepiosHttpBackend.from_environment()
    return HealthNavigator(backend=backend)
